# Generated by Django 2.2.4 on 2019-08-29 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190829_2046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
