# Generated by Django 2.2.4 on 2019-09-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('e_code', models.CharField(max_length=6)),
                ('available_load', models.CharField(max_length=2)),
            ],
        ),
    ]
