# Generated by Django 2.2.4 on 2019-09-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_teacherdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(max_length=32)),
                ('cls', models.CharField(max_length=32)),
            ],
        ),
    ]
